/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdint.h"
#include "stm32f103x8.h"
#include "stm32f103x8_gpio_driver.h"
#include "stm32f103x8_EXTI_driver.h"

#define SET_OS_PSP(ADD) __asm volatile("mov R0,%0 \n\t" \
										"msr PSP,R0" \
										:\
										:"r" (ADD) )

#define SET_MSP_PSP __asm("mrs R0,CONTROL \n\t" \
						  "mov R1,#0x02 \n\t "\
						  "orr R0,R1,R0 \n\t "\
						  "msr CONTROL,R0")

#define OS_Generate_Exception __asm("SVC #0x03")

#define SET_PSP_MSP __asm( "mrs R0,CONTROL \n\t" \
						  "mov R1,#0xFFFFFFFD \n\t "\
						  "and R0,R1,R0 \n\t "\
						  "msr CONTROL,R0")

extern int _estack;

#define TASKA 100
#define TASKB 100

unsigned int _S_MSP = & _estack;
unsigned int _E_MSP;

unsigned int _S_PSPA;
unsigned int _E_PSPA;

unsigned int _S_PSPB;
unsigned int _E_PSPB;

uint8_t TASKAF,TASKBF,IRQ_FLAG = 0;
int val=1;
int val2=0;



void EXTI9_Callback(void){


	if(!IRQ_FLAG){
		TASKAF = 1;
		IRQ_FLAG = 1;
	}
	else if (IRQ_FLAG){
		TASKBF = 1;
		IRQ_FLAG = 0;
	}

}

enum Switch_access_mode{
	priveleged,
	unpriveleged
};

void CPU_access_mode(enum Switch_access_mode level){

	switch(level){

	case priveleged:
		__asm("MRS R0,CONTROL \n\t "
			  "AND R0,R0,#0xFFFFFFFFE \n\t"
			  "MSR CONTROL,R0");
		break;
	case unpriveleged:
		__asm("MRS R0,CONTROL \n\t "
			  "ORR R0,R0,#0x01 \n\t"
			  "MSR CONTROL,R0");
		break;
	default:
		break;
	}

}
void SVC_Handler(){

	CPU_access_mode(priveleged);

}

int TaskA(int a,int b , int c){

	return a+b+c;

}

int TaskB(int d){

	return d+d+d;
}

void MainOS(){

	_E_MSP =_S_MSP- 512;

	_S_PSPA = _E_MSP - 8;
	_E_PSPA = _S_PSPA - TASKA;

	_S_PSPB = _E_PSPA - 8;
	_E_PSPB = _S_PSPB - TASKB;

	while(1)
	{
		//set PSP TO TASK
		//SP->PSP
		//Privileged -> unprivileged

		if(TASKAF == 1){
			SET_OS_PSP(_S_PSPA);
			SET_MSP_PSP;
			CPU_access_mode(unpriveleged);
			TASKAF = TaskA(1, 2, 3);
			//SP->MSP
			//unprivileged -> privileged
			OS_Generate_Exception;
			SET_PSP_MSP;
		}
		else if (TASKBF == 1){
			SET_OS_PSP(_S_PSPB);
			SET_MSP_PSP;
			CPU_access_mode(unpriveleged);
			TASKBF = TaskB(1);

			OS_Generate_Exception;
			SET_PSP_MSP;
		}
	}
}

int main(void)
{

	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	EXTI_PinConfig_t EXTIConfig;

	EXTIConfig.EXTI_PIN=EXTI9PB9;
	EXTIConfig.Trigger_Case=EXTI_Trigger_RISING;
	EXTIConfig.P_IRQ_CallBack=EXTI9_Callback;
	EXTIConfig.IRQ_EN=EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTIConfig);

	IRQ_FLAG = 1;
	CPU_access_mode(unpriveleged);
	CPU_access_mode(priveleged);

	MainOS();

	while(1){

		if(IRQ_FLAG)IRQ_FLAG=0;
		else;

	}
}
